# Generated by Django 5.0.6 on 2024-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.CharField(default='Precio: ', max_length=20),
        ),
    ]
