# Generated by Django 5.0.6 on 2024-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flan_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='customer_email',
            field=models.EmailField(help_text='Correo', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='customer_name',
            field=models.CharField(help_text='Nombre', max_length=64),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(help_text='Mensaje'),
        ),
    ]
