# Generated by Django 5.0.6 on 2024-06-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_contactform_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='customer_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(),
        ),
    ]
