# Generated by Django 5.0.6 on 2024-06-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_fotocarrusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='static_url',
            field=models.CharField(default='img/', max_length=50),
        ),
    ]
